name: SnakeAnimation

on:
  schedule:
    - cron: "0 */12 * * *"   # 2x ao dia é suficiente
  workflow_dispatch:
  push:
    branches:
      - main                 # ajuste se sua default é 'main'; mude para 'master' se for o caso

permissions:
  contents: write            # necessário para publicar na branch

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: luccas00
          outputs: |
            dist/src/github-contribution-grid-snake.svg
            dist/src/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
